[package]
edition = "2021"
name    = "node-rs_argon2"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
argon2 = { version = "0.5", features = ["rand"] }
global_alloc = { path = "../../crates/alloc" }
napi = { version = "2", default-features = false, features = ["napi3"] }
napi-derive = { version = "2", default-features = false, features = [
  "type-def",
] }
rand_core = { version = "0.6", features = ["getrandom"] }

[build-dependencies]
napi-build = "2"
