[package]
name = "simd-json"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
jemallocator = "0.3"
napi-rs = { path = "../../../napi-rs/napi", version = "0.2" }
serde_json = "1"
simd-json = "0.3"

[build-dependencies]
napi-build = { path = "../../../napi-rs/build", version = "0.1" }
